name: "Mendable Action"
description: "This action integrates AI powered issue solver"
author: "SideGuide Technologies Inc."

branding:
  icon: activity
  color: purple

inputs:
  number:
    description: "ID of Pull Request or Issue"
    required: true
  mode:
    description: "Mode"
    required: true
    default: "issues"
  mendableToken:
    description: "Mendable Token"
    required: true
    default: ""
    
outputs:
  comment:
    description: "The comment from chatgpt."
runs:
  using: "node16"
  main: "dist/index-o.js"
