# On issue opened
on:
  issues:
    types:
      - opened
  

name: Mendable Action

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Suggest solutions to issues - Mendable Action
    steps:
      - uses: actions/checkout@v2
      - name: Suggest solutions to issues - Mendable Action
        uses: ./
        id: mendable-action
        with:
          number: ${{ github.event.issue.number }}
          mendableToken: ${{ secrets.MENDABLE_TOKEN }}
          mode: 'issues'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 